INSERT INTO users (username,password, nombre, apellido, email ) VALUES('Paquin','1234','Paco', 'Fernandez', 'paco@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('saulin','1234','Saúl', 'Gutierrez', 'saul@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('marianin','1234','Mariano', 'Dominguez', 'mariano@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('beita','1234','Beatriz', 'Bernabeu', 'bea@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('lore','1234','Lorena', 'Savedra', 'lorena@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('antonin','1234','Antonio', 'Martinez', 'antonio@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('mariita','1234','María', 'Guzman', 'maria@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('adolfin','1234','Adolfo', 'de Lera', 'adolfo@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('vero','1234','Veronica', 'Guzman', 'vero@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('albita','1234','Alba', 'Alvarez', 'alba@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('andresin','1234','Andres', 'Barbas', 'andresr@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('vicentina','1234','Vicenta', 'Fernández', 'vicenta@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('quiquin','1234','Quique', 'Pozo', 'quiquin@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('josin','1234','José', 'Rios', 'jose@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('joaqui','1234','Joaquina', 'Toledana', 'joaquina@proyecto.com');
INSERT INTO users (username,password, nombre, apellido, email ) VALUES('pili','1234','Pilar', 'Rojas', 'pilar@proyecto.com');
